apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
  labels:
    app: clinic
spec:
  selector:
    matchLabels:
      app: clinic
  template:
    metadata:
      labels:
        app: clinic
    spec:
      containers:
      - name: martur-app
        image: martur/app:2
        ports:
        - containerPort: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: myapp-service
  labels:
    env: lb
spec:
  type: LoadBalancer

  selector:
    app: clinic
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 8080

---

apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: myapp
spec: 
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: myapp
  minReplicas: 1
  maxReplicas: 6
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 75

 