apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: clinic1
  region: eu-central-1

nodeGroups:
  - name: ng-1
    instanceType: m5.large
    desiredCapacity: 1
    volumeSize: 10


 