apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: clinic1
  region: eu-central-1

nodeGroups:
  - name: ng-1
    instanceType: c5a.xlarge
    desiredCapacity: 1
    volumeSize: 20


 