pipeline{
    agent any
    stages{
        // stage("package app"){
        //     steps{
        //         sh "mvn package"
        //         echo "========executing A========"
        //     }
            
        // }
        stage("create docker image"){
            steps{
                
                sh "docker build  -t martur/app:latest  -f docker/dockerfile ."
                echo "========executing A========"
            }
            
        }
        stage("push image to hub"){
            steps{
                sh "ls"
                echo "========executing A========"
            }
            
        }
        stage("kubectl"){
            steps{
                sh "ls"
                echo "========executing A========"
            }
            
        }
    }
    
}